/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SoftwareCompleto;

import Controller.ControladoresDaTarefa;
import Controller.ControladoresDoProjeto;
import Model.Projetos;
import Model.Tarefas;
import java.util.Date;
import java.util.List;

public class App {
    

    public static void main(String[] args) {
       
//  ControladoresDoProjeto controladores = new ControladoresDoProjeto();    
   
// SALVANDO PROJETOS
//  Projetos projetos = new Projetos();
//  projetos.setNOME("Projeto Teste");
//  projetos.setDESCRICAO("Descricao");
//  ControladoresDoProjeto.save(projetos);

 ControladoresDoProjeto controladoresDoProjeto = new ControladoresDoProjeto();
  
 // ATUALIZANDO PROJETOS
   Projetos projetos = new Projetos();
   projetos.setID(1);
   projetos.setNOME("Novo Nome Projeto");
   projetos.setDESCRICAO("Testando");
   ControladoresDoProjeto.update(projetos);
    
  // BUSCANDO PROJETOS  
  List<Projetos> projetosList = ControladoresDoProjeto.getAll();
  System.out.println("Total de Projetos = " + projetosList.size());
   
//  DELETANDO PROJETOS EXISTENTES             
//  ControladoresDoProjeto.removeByID(1);


    ControladoresDaTarefa controladoresDaTarefa = new ControladoresDaTarefa();;
 
   // SALVANDO TAREFAS 
   Tarefas tarefas = new Tarefas();
 //  tarefas.setIDPROJETO(2);
 //  tarefas.setNOME("Criar as Telas da Aplicação");
//   tarefas.setDESCRICAO("Devem ser criadas telas para os Cadastros");
//   tarefas.setNOTAS("Sem Notas");
//   tarefas.setCOMPLETED(false);
//   tarefas.setPRAZO(new Date());
//   ControladoresDaTarefa.save(tarefas);
 
 // ATUALIZANDO TAREFAS  
 tarefas.setNOME("Alterar telas da Aplicação");
 ControladoresDaTarefa.update(tarefas);
 
 
 // BUSCANDO TAREFAS
 List<Tarefas> tarefasList = ControladoresDaTarefa.getAll(5);
 System.out.println("Total de Tarefas = " + tarefasList.size());
 
 
    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
